docker_dir: "/home/ansible/docker"
project_name: "nextcloud"
mounted_dir: "/mnt/nextcloud_storage"

mariadb_user_passwd: ""
mariadb_root_passwd: ""

domain: "sub.example.com"
network_backend:
  name: ""
  ipam_options:
  - subnet: ""
    gateway: ""
  traefik_ips:
    traefik: "172.80.2.2"
    nextcloud: "172.80.2.3"