cloud_docker_dir: "/home/ansible/docker"

user_dns:
  name: "user_dns"
  port_num: "53"
  ts_ip: "172.20.0.4"
  upstream_server: "10.0.0.3"
  records: |
    address=/cloud.nerolab.dev/172.20.0.3
    address=/fog.nerolab.dev/172.20.1.3
    address=/media.nerolab.dev/172.20.2.3

cloud_tailscale_subnet:
  subnet_cidr: "172.20.0.0/24"
  gateway: "172.20.0.1"
  tailscale_ip: "172.20.0.2"
  traefik_ip: "172.20.0.3"
  dns_ip: "172.20.0.4,172.20.0.5,172.20.0.6"
  nextcloud_ip: "172.20.0.20"
  searxng_ip: "172.20.0.21"

cloud_domains:
  traefik: "traefik.cloud.nerolab.dev"
  main: "nerolab.dev"
  wildcard: "*.cloud.nerolab.dev"

nginx_cloud:
  cloud:
    traefik_ip: 172.20.0.3
    domains_list:
      - name: app1.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 192.168.1.10
          - 1.2.3.4            
  media:
    traefik_ip: 172.20.1.3
    domains_list:
      - name: app2.media.nerolab.dev
        allowed_tailscale_client_ips:
          - 192.168.1.11

cloud_nextcloud:
  name: "nextcloud"
  mounted_dir: "/mnt/nextcloud_storage"
  domain: "nextcloud.cloud.nerolab.dev"

cloud_searxng:
  name: "searxng"
  domain: "searxng.cloud.nerolab.dev"