cloud_docker_dir: "/home/ansible/docker"

# Tailscale Config for the below.

# autoApprovers routes
# "10.110.0.0/29": ["tag:cloud-server"], // traefik
# "10.110.1.0/29": ["tag:cloud-server"], // dns
# "10.110.20.0/28": ["tag:cloud-server"], // monitor-center

# hosts
# "cloud-traefik-net": "10.110.0.0/29",
# "cloud-dns-net": "10.110.1.0/29",
# "cloud-monitor-center-net": "10.110.20.0/28",

# "cloud-traefik": "10.110.0.2",
# "cloud-dns": "10.110.1.4",

# restricted nameserver (dns)
# 10.110.1.4


### MAIN VLAN NETWORK STACK

cloud_dns:
  name: "cloud_dns"
  port_num: "53"
  network_backend:
    name: "tailscale_dnsmasq"
    ipam_options:
    - subnet: "10.110.1.0/29"
      gateway: "10.110.1.1"
    tailscale_ips:
      tailscale: "10.110.1.2"
      dnsmasq: "10.110.1.4"
  upstream_server: "10.0.0.3"
  records: |
    # cloud domains to cloud traefik
    address=/cloud.nerolab.dev/10.110.0.2
    # this domain to monitor main stack traefik
    address=/monitor.nerolab.dev/10.110.0.2

# remember to
# - copy traefik shared ip to dns reverse proxy records
# - set tailscale acls, autoApprovers, hosts, and grants
cloud_networks:
  shared:
    - name: "traefik_tailscale"
      ipam_options:
      - subnet: "10.110.0.0/29"
        gateway: "10.110.0.1"
      traefik_ip: "10.110.0.2"
      tailscale_ip: "10.110.0.4"
      dns_ip: "10.110.0.5"
    - name: "{{cloud_monitor_center.network_backend.name}}"
      ipam_options: "{{cloud_monitor_center.network_backend.ipam_options}}"
      traefik_ip: "{{cloud_monitor_center.network_backend.ips.traefik}}"
      tailscale_ip: "{{cloud_monitor_center.network_backend.ips.tailscale}}"
  traefik_specific: # these containers don't have Tailscale DNS and connection-ability
    - name: "{{cloud_searxng.network_backend.name}}"
      ipam_options: "{{cloud_searxng.network_backend.ipam_options}}"
      traefik_ip: "{{cloud_searxng.network_backend.traefik_ips.traefik}}"
    - name: "{{cloud_nextcloud.network_backend.name}}"
      ipam_options: "{{cloud_nextcloud.network_backend.ipam_options}}"
      traefik_ip: "{{cloud_nextcloud.network_backend.traefik_ips.traefik}}"
  tailscale_specific:
    - name: "{{cloud_dns.network_backend.name}}"
      ipam_options: "{{cloud_dns.network_backend.ipam_options}}"
      tailscale_ip: "{{cloud_dns.network_backend.tailscale_ips.tailscale}}"

cloud_traefik:
  domains:
    main: "nerolab.dev"
    wildcard: "*.cloud.nerolab.dev"
    traefik: "traefik.cloud.nerolab.dev"
  dns:
    upstream_server: "10.0.0.3"
    config: |
      address=/cloud.nerolab.dev/10.110.0.2


#### USER GATEWAY ###

gate_name: "cloud_gate"

gate_dns_conf:
  ip: "100.80.1.1"
  upstream_server: "10.0.0.3"
  records: |
    address=/cloud.nerolab.dev/100.80.1.1
    address=/fog.nerolab.dev/100.80.1.1
    address=/media.nerolab.dev/100.80.1.1

gate_traefik_instances:
  cloud:
    traefik_ip: 10.110.0.2
    domains_list:
      - name: traefik.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
      - name: nextcloud.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
      - name: searxng.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
      - name: grafana.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
      - name: loki.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
  media:
    traefik_ip: 10.130.0.2
    domains_list:
      - name: traefik.media.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
      - name: searxng.media.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom


### MONITOR CENTER ###

cloud_monitor_center:
  name: "monitor_center"
  sub_role: "center"
  network_backend:
    name: "monitor_center"
    ipam_options:
    - subnet: "10.110.20.0/28"
      gateway: "10.110.20.1"
    ips:
      tailscale: "10.110.20.2"
      traefik: "10.110.20.3"
      grafana: "10.110.20.4"
      loki: "10.110.20.5"
      mimir: "10.110.20.6"
      alloy: "10.110.20.7"
      dns: "10.110.20.8"
  outpost_header: "cloud-outpost"
  domains:
    grafana: "grafana.cloud.nerolab.dev"
    loki: "loki.cloud.nerolab.dev"
    mimir: "mimir.cloud.nerolab.dev"
    alloy: "alloy.cloud.nerolab.dev"
  dns:
    upstream_server: "10.0.0.3"
    config: |
      address=/cloud.nerolab.dev/10.110.20.3


### END SERVICE SPECIFIC VARS ###

cloud_nextcloud:
  name: "nextcloud"
  mounted_dir: "/mnt/nextcloud_storage"
  domain: "nextcloud.cloud.nerolab.dev"
  network_backend:
    name: "t3_nextcloud"
    ipam_options:
    - subnet: "10.110.30.0/29"
      gateway: "10.110.30.1"
    traefik_ips:
      traefik: "10.110.30.3"
      nextcloud: "10.110.30.5"

cloud_searxng:
  name: "searxng"
  domain: "searxng.cloud.nerolab.dev"
  network_backend:
    name: "t3_searxng"
    ipam_options:
    - subnet: "10.110.31.0/29"
      gateway: "10.110.31.1"
    traefik_ips:
      traefik: "10.110.31.3"
      searxng: "10.110.31.5"