cloud_docker_dir: "/home/ansible/docker"

cloud_dns:
  name: "user_dns"
  port_num: "53"
  ts_ip: "172.20.0.4"
  upstream_server: "10.0.0.3"
  records: |
    address=/cloud.nerolab.dev/172.20.0.3

### MAIN VLAN NETWORK STACK

cloud_tailscale_subnet:
  subnet_cidr: "172.20.0.0/24"
  gateway: "172.20.0.1"
  tailscale_ip: "172.20.0.2"
  traefik_ip: "172.20.0.3"
  dns_ip: "172.20.0.4"
  nextcloud_ip: "172.20.0.20"
  searxng_ip: "172.20.0.21"

cloud_traefik_domains:
  main: "nerolab.dev"
  wildcard: "*.cloud.nerolab.dev"
  traefik: "traefik.cloud.nerolab.dev"


#### USER GATEWAY ###

gate_name: "cloud_gate"

gate_tailscale_subnet:
  name: "gate-tailscale-network"
  subnet_cidr: "172.30.0.0/29"
  gateway: "172.30.0.1"
  tailscale_ip: "172.30.0.2"
  dns_ip: "100.80.1.1"

gate_dns:
  upstream_server: "10.0.0.3"
  records: |
    address=/cloud.nerolab.dev/100.80.1.1
    address=/fog.nerolab.dev/100.80.1.1
    address=/media.nerolab.dev/100.80.1.1

gate_traefik_instances:
  cloud:
    traefik_ip: 172.20.0.3
    domains_list:
      - name: traefik.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
      - name: nextcloud.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
      - name: searxng.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom
  media:
    traefik_ip: 172.20.1.3
    domains_list:
      - name: app2.media.nerolab.dev
        allowed_tailscale_client_ips:
          - 100.93.170.126 # stardom


### SERVICE SPECIFIC VARS ###

cloud_nextcloud:
  name: "nextcloud"
  mounted_dir: "/mnt/nextcloud_storage"
  domain: "nextcloud.cloud.nerolab.dev"

cloud_searxng:
  name: "searxng"
  domain: "searxng.cloud.nerolab.dev"