media_docker_dir: "/home/ansible/docker"

### NETWORK STACK VARS ###

media_dns:
  name: "media_dns"
  port_num: "53"
  network_backend:
    name: "tailscale_dnsmasq"
    ipam_options:
    - subnet: "172.20.2.0/29"
      gateway: "172.20.2.1"
    tailscale_ips:
      tailscale: "172.20.2.2"
      dnsmasq: "172.20.2.4"
  upstream_server: "10.0.0.3"
  records: |
    # media domains to media traefik
    address=/media.nerolab.dev/172.30.1.2
    # this domain to monitor main stack traefik
    address=/monitor.nerolab.dev/172.30.1.2

media_tailscale_subnet:
  subnet_cidr: "172.20.2.0/28"
  gateway: "172.20.2.1"
  tailscale_ip: "172.20.2.2"
  traefik_ip: "172.20.2.3"
  dns_ip: "172.20.2.4"

# remember to
# - copy traefik shared ip to dns reverse proxy records
# - set tailscale acls, autoApprovers, hosts, and grants
media_networks:
  shared:
    - name: "traefik_tailscale"
      ipam_options:
      - subnet: "172.30.1.0/29"
        gateway: "172.30.1.1"
      traefik_ip: "172.30.1.2"
      tailscale_ip: "172.30.1.4"
  traefik_specific:
    - name: "{{media_searxng.network_backend.name}}"
      ipam_options: "{{media_searxng.network_backend.ipam_options}}"
      traefik_ip: "{{media_searxng.network_backend.traefik_ips.traefik}}"
  tailscale_specific:
    - name: "{{media_dns.network_backend.name}}"
      ipam_options: "{{media_dns.network_backend.ipam_options}}"
      tailscale_ip: "{{media_dns.network_backend.tailscale_ips.tailscale}}"

media_traefik:
  domains:
    main: "nerolab.dev"
    wildcard: "*.media.nerolab.dev"
    traefik: "traefik.media.nerolab.dev"

### END SERVICE SPECIFIC VARS ###

# media_nextcloud:
#   name: "nextcloud"
#   mounted_dir: "/mnt/nextcloud_storage"
#   domain: "nextcloud.media.nerolab.dev"
#   t3_network: "t3_nextcloud"
#   tailscale_ip: "172.20.2.8"

media_searxng:
  name: "searxng"
  domain: "searxng.media.nerolab.dev"
  network_backend:
    name: "t3_searxng"
    ipam_options:
    - subnet: "172.30.2.0/29"
      gateway: "172.30.2.1"
    traefik_ips:
      traefik: "172.30.2.3"
      searxng: "172.30.2.5"
