docker_dir: "/home/ansible/docker"

# Tailscale Config for the below.

# autoApprovers routes
# "10.130.0.0/29": ["tag:media-server"], // traefik
# "10.130.1.0/29": ["tag:media-server"], // dns
# "10.130.21.0/29": ["tag:media-server"], // monitor-outpost

# hosts
# "media-traefik-net": "10.130.0.0/29",
# "media-dns-net": "10.130.1.0/29",
# "media-monitor-outpost-net": "10.130.21.0/29",

# "media-traefik": "10.130.0.2",
# "media-traefik-monitor-outpost": "10.130.21.4",
# "media-dns": "10.130.1.4",


### MAIN VLAN NETWORK STACK

networks:
  shared:
    - name: "traefik_tailscale"
      ipam_options:
      - subnet: "10.130.0.0/29"
        gateway: "10.130.0.1"
      traefik_ip: "10.130.0.2"
      tailscale_ip: "10.130.0.3"
      dns_ip: "10.130.0.4"
  traefik_specific: # these containers don't have Tailscale DNS and connection-ability
    - name: "{{searxng.network_backend.name}}"
      ipam_options: "{{searxng.network_backend.ipam_options}}"
      traefik_ip: "{{searxng.network_backend.traefik_ips.traefik}}"
  tailscale_specific: ""

traefik:
  domains:
    main: "nerolab.dev"
    wildcard: "*.media.nerolab.dev"
    traefik: "traefik.media.nerolab.dev"
  dns:
    upstream_server: "10.0.0.3"
    config: |
      address=/media.nerolab.dev/10.130.0.2
      address=/monitor.media.nerolab.dev/10.130.21.2

# added to dhcp static mappings in opnsense
macvlan_network_center:
  name: "macvlan_network_center"
  parent_interface: "eth0"
  ip: "10.20.3.11"
  mac_address: "3a:d3:d3:3b:2a:5d"
  ipam_options:
  - subnet: "10.20.3.8/29"
    gateway: "10.20.3.9"


### MONITOR OUTPOST ###

monitor_outpost:
  name: "monitor_outpost"
  sub_role: "outpost"
  network_backend:
    name: "monitor_outpost"
    ipam_options:
    - subnet: "10.130.21.0/29"
      gateway: "10.130.21.1"
    traefik_ips:
      tailscale_traefik: "10.130.21.2"
      alloy: "10.130.21.3"
  outpost_header: "media-outpost"
  traefik_scrape_addresses:
    # don't use tailscale addresses here
    - "10.130.0.2" # network center 
    - "10.130.21.2" # monitor outpost
  tailscale_scrape_addresses:
    - "100.70.0.3" # media server - network center
    - "100.80.22.1" # media monitor outpost
    - "100.80.23.1" # media monitor alloy
  domains:
    main: "media.nerolab.dev"
    wildcard: "*.monitor.media.nerolab.dev"
    traefik: "traefik.monitor.media.nerolab.dev"
    loki: "loki.monitor.media.nerolab.dev"
    loki_forward: "loki.cloud.nerolab.dev"
    mimir: "mimir.monitor.media.nerolab.dev"
    mimir_forward: "mimir.cloud.nerolab.dev"

# added to dhcp static mappings in opnsense
macvlan:
  name: "macvlan_outpost"
  parent_interface: "eth1"
  ip: "10.20.3.19"
  mac_address: "32:97:96:6e:dc:45"
  ipam_options:
  - subnet: "10.20.3.16/29"
    gateway: "10.20.3.17"

# added to dhcp static mappings in opnsense
alloy_macvlan:
  ip: "10.20.3.20"
  mac_address: "be:10:0b:74:d7:bb"

### END SERVICE SPECIFIC VARS ###

searxng:
  name: "searxng"
  domain: "searxng.media.nerolab.dev"
  network_backend:
    name: "t3_searxng"
    ipam_options:
    - subnet: "10.130.31.0/29"
      gateway: "10.130.31.1"
    traefik_ips:
      traefik: "10.130.31.3"
      searxng: "10.130.31.5"
