traefik_instances:
  cloud:
    traefik_ip: 172.20.0.3
    domains_list:
      - name: app1.cloud.nerolab.dev
        allowed_tailscale_client_ips:
          - 192.168.1.10  # stardom
          - 1.2.3.4       # starfief            
  media:
    traefik_ip: 172.20.1.3
    domains_list:
      - name: app2.media.nerolab.dev
        allowed_tailscale_client_ips:
          - 192.168.1.11  # stardom
