---
- name: Disk Mount
  hosts: personal-cloud
  tasks:
    - name: Create an ext4 file-sys on /dev/sdb
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb
    - name: Mount 4TB sdb disk for Nextcloud Storage
      ansible.posix.mount:
        path: /mnt/nextcloud_storage
        src: /dev/sdb
        fstype: ext4
        state: mounted