- hosts: personal-cloud
  
  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - ansible

  roles:
    - geerlingguy.pip
    - geerlingguy.docker


  tasks:
    - name: Creates remote project directory
      ansible.builtin.file:
        path: '/home/ansible/docker'
        state: directory