---
- name: Nextcloud Setup
  vars:
    #TODO: service groups variables (arrays)
    target_compose_dir: "/home/ansible/docker"
  hosts: personal-cloud
  tasks:
    - name: Get source code absolute path
      shell: dirname '{{inventory_dir}}'
      register: dirname

    - name: Creates remote docker projects directory
      ansible.builtin.file:
        path: '{{target_compose_dir}}'
        state: directory

### Nextcloud Setup ###

    - name: Creates remote Nextcloud project directory
      ansible.builtin.file:
        path: '{{target_compose_dir}}/nextcloud'
        state: directory

    - name: copy Nextcloud Docker Compose files
      copy:
        src: "{{dirname.stdout}}/docker/{{ item }}"
        dest: "{{target_compose_dir}}/nextcloud/{{ item }}"
      loop:
        - nextcloud_stack.yml

    - name: Load Sops Secrets
      community.sops.load_vars:
        file: ../../secrets/secrets.yaml
        name: sops_secrets
        expressions: ignore  # explicitly do not evaluate expressions
                            # on load (this is the default)

    - name: Creates remote Nextcloud data directory
      ansible.builtin.file:
        path: '{{target_compose_dir}}/nextcloud/data'
        state: directory

    - name: Create mariadb_root_passwd file
      ansible.builtin.copy:
        content: "{{ sops_secrets.mariadb_root_passwd }}"
        dest: "{{target_compose_dir}}/nextcloud/data/mariadb_root_passwd.txt"

    - name: Create mariadb_user_passwd file
      ansible.builtin.copy:
        content: "{{ sops_secrets.mariadb_user_passwd }}"
        dest: "{{target_compose_dir}}/nextcloud/data/mariadb_user_passwd.txt"

    - name: Wipe Sops Secrets from Ansible's facts
      # This is particularly important if the playbook doesn't end here!
      set_fact:
        sops_secrets: ''

    - name: Deploy Nextcloud Docker Compose stack
      community.docker.docker_compose_v2:
        project_name: nextcloud
        project_src: '{{target_compose_dir}}/nextcloud'
        files:
          - nextcloud_stack.yml