---
- name: Traefik Setup
  vars:
    #TODO: service groups variables (arrays)
    target_compose_dir: "/home/ansible/docker"
  hosts: personal-cloud
  tasks:
    - name: Get source code absolute path
      shell: dirname '{{inventory_dir}}'
      register: dirname

    - name: Creates remote docker projects directory
      ansible.builtin.file:
        path: '{{target_compose_dir}}'
        state: directory

### Traefik Setup ###

    - name: Creates remote Traefik project directory
      ansible.builtin.file:
        path: '{{target_compose_dir}}/traefik'
        state: directory

    - name: copy Traefik Docker Compose files
      ansible.builtin.copy:
        src: "{{dirname.stdout}}/docker/traefik.yml"
        dest: "{{target_compose_dir}}/traefik/traefik_compose.yml"

    - name: Load Sops Secrets
      community.sops.load_vars:
        file: ../../secrets/secrets.yaml
        name: sops_secrets
        expressions: ignore  # explicitly do not evaluate expressions
                            # on load (this is the default)

    - name: Create .env file with traefik dhashboard credentials
      ansible.builtin.copy:
        content: "{{ sops_secrets.TRAEFIK_DASHBOARD_CREDENTIALS }}"
        dest: "{{target_compose_dir}}/traefik/.env"

    - name: Create api_token file
      ansible.builtin.copy:
        content: "{{ sops_secrets.desec_api_token }}"
        dest: "{{target_compose_dir}}/traefik/desec_api_token.txt"

    - name: Wipe Sops Secrets from Ansible's facts
      # This is particularly important if the playbook doesn't end here!
      set_fact:
        sops_secrets: ''

    - name: Creates remote Traefik data directory
      ansible.builtin.file:
        path: '{{target_compose_dir}}/traefik/data'
        state: directory

    - name: Creates acme.json file with correct permissions
      ansible.builtin.file:
        path: '{{target_compose_dir}}/traefik/data/acme.json'
        state: touch
        mode: '600'

    - name: Copy traefik.yml (config) file
      ansible.builtin.copy:
        src: "{{dirname.stdout}}/configs/traefik.yml"
        dest: "{{target_compose_dir}}/traefik/data/traefik.yml"


    - name: Create t3_proxy docker network
      docker_network:
        name: t3_proxy

    - name: deploy Traefik Docker Compose stack
      community.docker.docker_compose_v2:
        project_name: traefik
        project_src: '{{target_compose_dir}}/traefik'
        files:
          - traefik_compose.yml