#TODO: make container name variable and local network
- name: Delete default ip route
  community.docker.docker_container_exec:
    container: 'ts-gate'
    command: "ip route delete default"
    chdir: /

- name: Container get eth device number
  ansible.builtin.raw: "docker exec ts-gate ip r | grep {{macvlan.ip}} | awk '{print $3}'"
  register: eth_num

- name: Add desired default ip route
  community.docker.docker_container_exec:
    container: 'ts-gate'
    command: "ip route add default via {{macvlan.ipam_options[0].gateway}} dev {{eth_num.stdout}}"
    chdir: /