---
- name: Monitor Stack Setup
  vars:
    docker_dir: "/home/ansible/docker"
    stack_dir: "/home/ansible/docker/monitor_stack"
    project_name: "monitor_stack"
    local_docker_dir: "/docker/monitor_stack"
  hosts: personal-cloud
  tasks:

    ### BOILER PLATE ###
    - name: Get source code absolute path
      shell: dirname '{{inventory_dir}}'
      register: dirname

    - name: Update local docker directory name variable
      ansible.builtin.set_fact:
        local_docker_dir: "{{ [dirname.stdout, local_docker_dir] | join('') }}"

    - name: Creates remote docker projects directory
      ansible.builtin.file:
        path: '{{docker_dir}}'
        state: directory

    ### HANDLE COMPOSE AND CONFIG FILES ###
    - name: Creates remote Monitor Stack project directory
      ansible.builtin.file:
        path: '{{stack_dir}}'
        state: directory

    - name: Copy Monitor Stack docker compose file
      ansible.builtin.copy:
        src: "{{local_docker_dir}}/"
        dest: "{{stack_dir}}/"
      loop:
        - compose.yml

    - name: Copy loki-config.yaml file
      ansible.builtin.copy:
        src: "{{local_docker_dir}}/"
        dest: "{{stack_dir}}/"
      loop:
        - loki-config.yaml

    - name: Copy config.alloy file
      ansible.builtin.copy:
        src: "{{local_docker_dir}}/"
        dest: "{{stack_dir}}/"
      loop:
        - config.alloy

    ### DEPLOY ###
    - name: Deploy Monitor Stack Docker Compose stack
      community.docker.docker_compose_v2:
        project_name: '{{project_name}}'
        project_src: '{{stack_dir}}'
        files:
          - compose.yml