docker_dir: "/home/ansible/docker"
project_name: "dns_01"

tailscale_network_name: "tailscale-network"
tailscale_ip: "172.20.0.4"

host_num: "53"

upstream_server: "10.0.0.3"

dns_records: |
  # A records
  address=/cloud.nerolab.dev/10.20.1.20

  # CNAME records
  cname=nginx.cloud.nerolab.dev,cloud.nerolab.dev