services:
  alpine:
    image: alpine:latest
    container_name: alpine
    tty: true
    networks:
      tailscale-network:
        ipv4_address: 172.20.1.10
      t3_proxy:

networks:
  tailscale-network:
    external: true
  t3_proxy:
    external: true