
# Manual Work In Wizard (not env vars because of broken secrets support)
# - For the database use nextcloud-db as host and nextcloud as table and
#   user name and enter the MYSQL_PASSWORD from your docker-compose.yml.

# Services (containers) we would like this document to run
services:
  ## All services/containers go below this line (note the two space indentation in front).

  # Nextcloud Docker Application
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    # Defines how we want our container to connect outside
    networks:
      # Use an internal network for the nextcloud services
      - nextcloud_backend
      - t3_proxy
    # Persistent volumes with bind mounts to easily move/backup data
    volumes:
      - /mnt/nextcloud_storage/html:/var/www/html
      - /mnt/nextcloud_storage/custom_apps:/var/www/html/custom_apps
      - /mnt/nextcloud_storage/config:/var/www/html/config
      - /mnt/nextcloud_storage/data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.nerolab.dev
      REDIS_HOST: nextcloud-redis
      REDIS_PORT: 6379
    links:
      - nextcloud-db
      - nextcloud-redis
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.ts.nerolab.dev`)"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=desec"

  # Nextcloud Database
  nextcloud-db:
    image: mariadb:11.4
    container_name: nextcloud-db
    hostname: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=msqyld-bin --binlog-format=ROW
    networks:
      - nextcloud_backend
    volumes:
      - ./nextcloud_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_passwd
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_user_passwd
    secrets:
      - mariadb_root_passwd
      - mariadb_user_passwd

  nextcloud-redis:
    hostname: nextcloud-redis
    container_name: nextcloud-redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nextcloud_backend
    expose:
      - 6379

secrets:
  mariadb_root_passwd:
    file: ./data/mariadb_root_passwd.txt
  mariadb_user_passwd:
    file: ./data/mariadb_user_passwd.txt

networks:
  nextcloud_backend:
    driver: bridge
  t3_proxy:
    external: true
