services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      tailscale-network:
        ipv4_address: 172.20.0.7
      searxng_backend:
      t3_proxy:
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - UWSGI_WORKERS=2
      - UWSGI_THREADS=2
      # - BASE_URL=searxng.ts.nerolab.dev
    # must be run this way first time, then uncommented and ran with
    # docker compose -f searxng_stack.yml up -d
    # cap_drop:
    #   - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`searxng.ts.nerolab.dev`)"
      - "traefik.http.routers.searxng.entrypoints=https"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.routers.searxng.tls.certresolver=desec"

networks:
  searxng_backend:
  tailscale-network:
    external: true
  t3_proxy:
    external: true