### BOILER PLATE ###
- name: Creates remote docker projects directory
  ansible.builtin.file:
    path: '{{docker_dir}}'
    state: directory

- name: Update local docker directory name variable
  ansible.builtin.set_fact:
    stack_dir: "{{ [docker_dir, project_name] | join('/') }}"

- name: Creates remote project directory
  ansible.builtin.file:
    path: '{{stack_dir}}'
    state: directory

- name: Transfer and convert the docker compose jinja2 template
  ansible.builtin.template:
    src: "compose.yml"
    dest: "{{stack_dir}}/compose.yml"

### MAIN ###
- name: Creates remote project directory
  ansible.builtin.file:
    path: '{{stack_dir}}/ts-nginx'
    state: directory

- name: Creates remote project directory
  ansible.builtin.file:
    path: '{{stack_dir}}/dnsmasq_image'
    state: directory

- name: Copy a file to a remote loc (and render if template)
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "{{stack_dir}}/./nginx.conf"

- name: Copy a file to a remote loc (and render if template)
  ansible.builtin.template:
    src: "dnsmasq.conf.j2"
    dest: "{{stack_dir}}/dnsmasq_image/dnsmasq.conf"

- name: Copy a file to a remote loc (and render if template)
  ansible.builtin.copy:
    src: "Dnsmasq_Dockerfile"
    dest: "{{stack_dir}}/dnsmasq_image/Dockerfile"

### MAIN ###

#TODO: check if this task is required
- name: Create network backend
  community.docker.docker_network:
    name: "{{network_backend.name}}"
    ipam_config: "{{network_backend.ipam_options}}"

- name: Create .env file with ts_authkey
  ansible.builtin.copy:
    dest: "{{stack_dir}}/.env"
    content: |
      TS_AUTHKEY={{ ts_auth_key }}

### DNS CONFIG

- name: Add records to dnsmasq.conf file
  ansible.builtin.lineinfile:
    path: "{{stack_dir}}/dnsmasq_image/dnsmasq.conf"
    line: "{{ dns.records }}"

- name: Build custom dnsmasq image
  docker_image:
    build:
      path: '{{stack_dir}}/dnsmasq_image'
    name: "custom/dnsmasq"
    tag: latest
    source: build
    force_source: true
    force_tag: true

- name: Create a docker MACVLAN for tailscale direct connections
  community.docker.docker_network:
    name: "{{ macvlan.name }}"
    ipam_config: "{{ macvlan.ipam_options }}"
    driver: "macvlan"
    driver_options:
      parent: "{{ macvlan.parent_interface }}"

### DEPLOY ###
- name: Deploy Docker Compose Stack
  community.docker.docker_compose_v2:
    project_name: '{{project_name}}'
    project_src: '{{stack_dir}}'
    files:
    - compose.yml


#TODO: make container name variable and local network
- name: Delete default ip route
  community.docker.docker_container_exec:
    container: 'ts-gate'
    command: "ip route delete default"
    chdir: /

- name: Container get eth device number
  ansible.builtin.raw: "docker exec ts-gate ip r | grep {{macvlan.ip}} | awk '{print $3}'"
  register: eth_num

- name: Add desired default ip route
  community.docker.docker_container_exec:
    container: 'ts-gate'
    command: "ip route add default via {{macvlan.ipam_options[0].gateway}} dev {{eth_num.stdout}}"
    chdir: /

