docker_dir: "/home/ansible/docker"
project_name: "edgeshark"

domains:
  edgeshark: "edgeshark.cloud.nerolab.dev"
  wireshark: "wireshark.cloud.nerolab.dev"

ts_auth_key: ""

macvlan:
  name: ""
  parent_interface: ""
  ip: ""
  mac_address: ""
  ipam_options:
  - subnet: ""
    gateway: ""

network_backend:
  name: "edgeshark"
  ipam_options:
  - subnet: "10.110.2.0/29"
    gateway: "10.110.2.1/29"
  traefik_ips:
    traefik: "10.110.2.2"
    ts_shark: "10.110.2.3"
    wireshark: "10.110.2.1"
