- name: Deploy to cloud host
  hosts: cloud
  gather_facts: true

  tasks:
    - name: Load Sops Secrets
      community.sops.load_vars:
        file: "{{ playbook_dir }}/../../secrets/secrets.yaml"
        name: sops_secrets
        expressions: ignore  # explicitly do not evaluate expressions
                            # on load (this is the default)


    # - name: Include Debian-Server Role
    #   include_role:
    #     name: debian_server
    #   vars:
    #     swap_file_size_mb: '1024'

    #FIXME: add some wait time here before network role for dns propagation

    # - name: Include Network Role
    #   include_role:
    #     name: network
    #   vars:
    #     TRAEFIK_DASHBOARD_CREDENTIALS: "{{ sops_secrets.TRAEFIK_DASHBOARD_CREDENTIALS }}"
    #     ts_auth_key: "{{ sops_secrets.cloud_server_ts_auth_key }}"
    #     desec_api_token: "{{ sops_secrets.desec_api_token }}"
    #     docker_dir: "{{cloud_docker_dir}}"
    #     domains:
    #       main: "{{ cloud_traefik.domains.main }}"
    #       wildcard: "{{ cloud_traefik.domains.wildcard }}"
    #       traefik: "{{ cloud_traefik.domains.traefik }}"
    #     dns: "{{cloud_traefik.dns}}"
    #     networks: "{{cloud_networks}}"
    #     macvlan: "{{cloud_macvlan_network_center}}"

    # - name: Include NGINX Gate Role - User Gateway
    #   include_role:
    #     name: nginx_gate
    #   vars:
    #     docker_dir: "{{cloud_docker_dir}}"
    #     project_name: "{{gate_name}}"
    #     traefik_instances: "{{ gate_traefik_instances }}"
    #     ts_auth_key: "{{ sops_secrets.cloud_gate_server_ts_auth_key }}"
    #     dns:
    #       ip: "{{ gate_dns_conf.ip }}"
    #       upstream_server: "{{ gate_dns_conf.upstream_server }}"
    #       records: "{{ gate_dns_conf.records }}"
    #     macvlan: "{{cloud_macvlan_user_gate}}"

    # - name: Include Edgeshark Role
    #   include_role:
    #     name: edgeshark
    #   vars:
    #     ts_auth_key: "{{ sops_secrets.cloud_shark_server_ts_auth_key }}"
    #     docker_dir: "{{cloud_docker_dir}}"
    #     project_name: "{{cloud_edgeshark.name}}"
    #     domains: "{{cloud_edgeshark.domains}}"
    #     network_backend: "{{ cloud_edgeshark.network_backend }}"
    #     macvlan: "{{cloud_macvlan_edgeshark}}"

    # - name: Include Monitor Center Role
    #   include_role:
    #     name: monitor
    #   vars:
    #     ts_auth_key: "{{ sops_secrets.cloud_server_monitor_center_ts_auth_key }}"
    #     docker_dir: "{{cloud_docker_dir}}"
    #     project_name: "{{cloud_monitor_center.name}}"
    #     sub_role: "{{cloud_monitor_center.sub_role}}"
    #     shared_network_backend: "{{cloud_monitor_center.network_backend}}"
    #     outpost_header: "{{cloud_monitor_center.outpost_header}}"
    #     domains: "{{cloud_monitor_center.domains}}"
    #     traefik_scrape_addresses: "{{cloud_monitor_center.traefik_scrape_addresses}}"
    #     tailscale_scrape_addresses: "{{cloud_monitor_center.tailscale_scrape_addresses}}"
    #     dns: "{{cloud_monitor_center.dns}}"
    #     macvlan: "{{cloud_macvlan_monitor_center}}"

    # - name: Include SearXNG Role
    #   include_role:
    #     name: searxng
    #   vars:
    #     docker_dir: "{{cloud_docker_dir}}"
    #     project_name: "{{cloud_searxng.name}}"
    #     domain: "{{cloud_searxng.domain}}"
    #     network_backend: "{{ cloud_searxng.network_backend }}"

# ---

    - name: Include Vikunja Role
      include_role:
        name: vikunja
      vars:
        docker_dir: "{{cloud_docker_dir}}"
        project_name: "{{cloud_vikunja.name}}"
        domain: "{{cloud_vikunja.domain}}"
        network_backend: "{{ cloud_vikunja.network_backend }}"