docker_dir: ""
project_name: ""

sub_role: ""

t3_network_backend:
  name: ""
  ipam_options:
  - subnet: ""
    gateway: ""
  traefik_ips:
    tailscale_traefik: "172.80.2.2"
    alloy: "172.80.2.3"

shared_network_backend:
  name: ""
  ipam_options:
  - subnet: ""
    gateway: ""
  ips:
    tailscale: "172.80.2.2"
    traefik: "172.80.2.3"
    grafana: ""
    loki: ""
    alloy: ""
    dns: ""

domains:
  grafana: ""
  loki: ""
  alloy: ""

outpost_header: ""

TRAEFIK_DASHBOARD_CREDENTIALS: ""
ts_auth_key: ""
desec_api_token: ""

dns:
  upstream_server: "10.0.0.3"
  config: |
    address=/cloud.nerolab.dev/10.20.1.20

macvlan:
  name: ""
  parent_interface: ""
  ip: ""
  mac_address: ""
  ipam_options:
  - subnet: ""
    gateway: ""