services:

  socket-proxy-outpost:
    image: "11notes/socket-proxy:2.1.1@sha256:6914fa5e6c57bdc0be40554ed720f87a0dc639d87654d77beffa14c1b85b1448"
    container_name: socket-proxy-outpost
    network_mode: "none"
    restart: "always"
    read_only: true
    user: "0:994"
    volumes:
      - "/run/docker.sock:/run/docker.sock:ro" # mount host docker socket, the :ro does not mean read-only for the socket, just for the actual file
      - "socket-proxy:/run/proxy" # this socket is run as 1000:1000, not as root!

  traefik-outpost:
    image: traefik:v3.4
    container_name: traefik-outpost
    depends_on:
      socket-proxy-outpost:
        condition: "service_healthy"
        restart: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - "80/tcp"
      - "443/tcp"
    networks:
      {{ts_network_backend.name}}:
        ipv4_address: {{ts_network_backend.tailscale_ips.alloy}}
      t3_proxy_outpost:
    volumes:
      - "socket-proxy:/var/run" # access docker socket via proxy read-only
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.zone.outpost=true"
      - "traefik.docker.network=t3_proxy_outpost"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    depends_on:
      socket-proxy-outpost:
        condition: "service_healthy"
        restart: true
    volumes:
      - './config.alloy:/etc/alloy/config.alloy'
      - "socket-proxy:/var/run"
    networks:
      t3_proxy_outpost:
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    labels:
      - "traefik.enable=true"
      - "traefik.zone.outpost=true"
      - "traefik.docker.network=t3_proxy_outpost"
      # Forward log pushes to the trusted Traefik instance (instead of Loki directly)
      - "traefik.http.routers.alloy-loki.entrypoints=http"
      - "traefik.http.routers.alloy-loki.rule=Path(`/loki/api/v1/push`)"
      - "traefik.http.routers.alloy-loki.service=trusted-traefik-forward"
      - "traefik.http.services.trusted-traefik-forward.loadbalancer.server.url=https://monitor.nerolab.dev"
      # Add middleware
      - "traefik.http.routers.alloy-loki.middlewares=add-tenant-header,rate-limit"
      # Tenant tagging
      - "traefik.http.middlewares.add-tenant-header.headers.customrequestheaders.X-Scope-OrgID={{outpost_header}}"
      # Rate limiting (still on untrusted side)
      - "traefik.http.middlewares.rate-limit.ratelimit.average=100"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=200"

volumes:
  socket-proxy:

networks:
  t3_proxy_outpost:
    external: true
  {{ts_network_backend.name}}:
    external: true